namespace Clean.Core.Storage;

// Offline knowledge about common applications and games. Keys are compared against folder names,
// executable names and installed program names, once reduced to lowercase letters and digits.
internal static class AppCatalog
{
    private const string Game = "Jeu";
    private const string Launcher = "Lanceur de jeux";
    private const string Browser = "Navigateur web";
    private const string Chat = "Messagerie";
    private const string Media = "Multimédia";
    private const string Driver = "Pilotes et matériel";
    private const string Dev = "Outil de développement";
    private const string Creative = "Création";
    private const string Utility = "Utilitaire";
    private const string Office = "Bureautique";
    private const string Cloud = "Stockage en ligne";

    public static IReadOnlyList<AppProfile> Profiles { get; } =
    [
        // Games and launchers
        App("FiveM", Game,
            "Une plateforme pour jouer à GTA V en ligne sur des serveurs modifiés par la communauté (roleplay, courses, mini-jeux…).",
            "Le gros de la place vient de FiveM.app\\data\\cache, qui grossit à chaque serveur visité : il peut être vidé quand FiveM est fermé, les fichiers se retéléchargent au besoin. Pour tout enlever, désinstalle FiveM.",
            "fivem", "citizenfx"),
        App("Grand Theft Auto V", Game,
            "Le jeu GTA V de Rockstar Games, en solo et en ligne (GTA Online).",
            "Le jeu pèse à lui seul plus de 100 Go. Pour libérer cette place, désinstalle-le depuis le lanceur utilisé (Rockstar, Steam ou Epic).",
            "grandtheftautov", "grandtheftautovenhanced", "gtav", "gta5"),
        App("Rockstar Games Launcher", Launcher,
            "Le lanceur de Rockstar Games, qui installe et met à jour GTA V, Red Dead Redemption 2 et les autres jeux Rockstar.",
            "Le lanceur lui-même est léger ; ce sont les jeux qui prennent de la place. Désinstalle-les depuis le lanceur.",
            "rockstargameslauncher", "rockstargames", "rockstar"),
        App("Riot Games", Launcher,
            "Le lanceur de Riot Games (Riot Client), qui installe VALORANT, League of Legends et leurs mises à jour.",
            "Chaque jeu Riot pèse plusieurs dizaines de Go. Désinstalle un jeu depuis Paramètres › Applications ou le Riot Client ; l'anti-triche Vanguard se désinstalle séparément.",
            "riotgames", "riotclient"),
        App("VALORANT", Game,
            "Le jeu de tir tactique en ligne de Riot Games.",
            "Pour libérer sa place (environ 50 Go), désinstalle VALORANT depuis Paramètres › Applications, puis Riot Vanguard si tu ne joues plus à aucun jeu Riot.",
            "valorant", "valo"),
        App("League of Legends", Game,
            "Le jeu de stratégie en ligne (MOBA) de Riot Games.",
            "Désinstalle-le depuis Paramètres › Applications si tu n'y joues plus.",
            "leagueoflegends", "lol"),
        App("Steam", Launcher,
            "La plateforme de jeux de Valve : boutique, bibliothèque de jeux, mises à jour et fonctions sociales.",
            "La place est prise par les jeux (steamapps\\common) et les mods du Workshop. Désinstalle les jeux depuis Steam ; le cache des shaders (steamapps\\shadercache) peut aussi être vidé.",
            "steam", "valve"),
        App("Epic Games Launcher", Launcher,
            "Le lanceur d'Epic Games, qui installe Fortnite, les jeux offerts chaque semaine et l'Unreal Engine.",
            "Désinstalle les jeux depuis le lanceur Epic. Le dossier de logs et le cache du lanceur restent petits.",
            "epicgameslauncher", "epicgames"),
        App("Fortnite", Game,
            "Le jeu de bataille royale d'Epic Games.",
            "Pèse souvent plus de 30 Go. Désinstalle-le depuis le lanceur Epic Games si tu n'y joues plus.",
            "fortnite"),
        App("Minecraft", Game,
            "Le jeu de construction de Mojang (Microsoft).",
            "Le jeu est léger, mais les mondes, mods et packs de ressources dans .minecraft peuvent grossir. Garde tes mondes (dossier saves) si tu y tiens.",
            "minecraft", "minecraftlauncher"),
        App("Counter-Strike 2", Game,
            "Le jeu de tir compétitif de Valve.",
            "Désinstalle-le depuis Steam si tu n'y joues plus.",
            "counterstrike2", "counterstrikeglobaloffensive", "csgo", "cs2"),
        App("Call of Duty", Game,
            "La série de jeux de tir d'Activision, souvent installée via Battle.net ou Steam.",
            "Parmi les jeux les plus lourds (plus de 100 Go). Désinstalle les modes inutiles depuis le lanceur pour gagner beaucoup de place.",
            "callofduty", "modernwarfare", "warzone"),
        App("Battle.net", Launcher,
            "Le lanceur de Blizzard et d'Activision (World of Warcraft, Overwatch, Diablo, Call of Duty…).",
            "Désinstalle les jeux depuis Battle.net.",
            "battlenet", "blizzard"),
        App("EA app", Launcher,
            "Le lanceur d'Electronic Arts (EA SPORTS FC, Apex Legends, Battlefield, Les Sims…).",
            "Désinstalle les jeux depuis l'EA app.",
            "eaapp", "electronicarts", "eadesktop"),
        App("Ubisoft Connect", Launcher,
            "Le lanceur d'Ubisoft (Assassin's Creed, Rainbow Six, Far Cry…).",
            "Désinstalle les jeux depuis Ubisoft Connect.",
            "ubisoftconnect", "ubisoftgamelauncher", "ubisoft", "uplay"),
        App("GOG Galaxy", Launcher,
            "Le lanceur de GOG, qui vend des jeux sans protection anticopie.",
            "Désinstalle les jeux depuis GOG Galaxy.",
            "goggalaxy", "gog"),
        App("Apex Legends", Game, "Le jeu de bataille royale de Respawn (EA).", "Désinstalle-le depuis l'EA app ou Steam.", "apexlegends"),
        App("Rocket League", Game, "Le jeu de football en voitures de Psyonix (Epic Games).", "Désinstalle-le depuis le lanceur Epic Games.", "rocketleague"),
        App("Overwolf", Utility,
            "Une plateforme d'applications qui s'affichent par-dessus les jeux (statistiques, enregistrement, CurseForge…).",
            "Les enregistrements vidéo et les mods téléchargés peuvent prendre beaucoup de place : vérifie les réglages de capture.",
            "overwolf", "curseforge"),
        App("Medal.tv", Media,
            "Un logiciel qui enregistre automatiquement tes meilleurs moments de jeu.",
            "Les clips enregistrés s'accumulent vite : supprime les anciens depuis Medal ou réduis la durée de conservation.",
            "medal", "medaltv"),

        // Browsers
        App("Google Chrome", Browser,
            "Le navigateur web de Google.",
            "Son cache se vide depuis Chrome (Paramètres › Confidentialité › Supprimer les données de navigation › Images et fichiers en cache) sans toucher à tes mots de passe ni à tes favoris.",
            "googlechrome", "chrome"),
        App("Microsoft Edge", Browser,
            "Le navigateur web de Microsoft, intégré à Windows.",
            "Son cache se vide depuis Edge (Paramètres › Confidentialité › Effacer les données de navigation). Ne le désinstalle pas : Windows en dépend.",
            "microsoftedge", "msedge", "edge"),
        App("Mozilla Firefox", Browser,
            "Le navigateur web libre de Mozilla.",
            "Son cache se vide depuis Firefox (Paramètres › Vie privée › Cookies et données de sites › Effacer les données).",
            "mozillafirefox", "firefox"),
        App("Brave", Browser,
            "Un navigateur web basé sur Chromium, axé sur la vie privée et le blocage des publicités.",
            "Son cache se vide depuis Brave (Paramètres › Confidentialité › Effacer les données de navigation).",
            "bravesoftware", "bravebrowser", "brave"),
        App("Opera", Browser,
            "Le navigateur Opera (ou Opera GX, sa version pour les joueurs).",
            "Opera GX a un « GX Cleaner » intégré qui vide le cache en un clic.",
            "operagx", "opera"),

        // Communication and media
        App("Discord", Chat,
            "Une messagerie vocale et textuelle très utilisée par les joueurs.",
            "Discord garde plusieurs anciennes versions (dossiers app-x.x.x) et un cache d'images qui grossit. Les anciennes versions et le cache peuvent être supprimés quand Discord est fermé.",
            "discord"),
        App("Spotify", Media,
            "Le service de streaming musical.",
            "Le cache des morceaux (dossier Data) peut atteindre plusieurs Go : réduis sa taille ou vide-le dans Spotify › Paramètres › Stockage.",
            "spotify"),
        App("WhatsApp", Chat, "La messagerie de Meta sur ordinateur.", "Les photos et vidéos reçues sont stockées localement : supprime les conversations ou médias inutiles depuis l'application.", "whatsapp"),
        App("Telegram", Chat, "Une messagerie en ligne.", "Le cache des médias se vide dans Paramètres › Avancé › Gérer le stockage local.", "telegramdesktop", "telegram"),
        App("Microsoft Teams", Chat, "La messagerie et visioconférence de Microsoft.", "Le cache de Teams se reconstruit tout seul ; désinstalle Teams si tu ne l'utilises pas.", "microsoftteams", "teams", "msteams"),
        App("Zoom", Chat, "Un logiciel de visioconférence.", "Les enregistrements de réunions sont rangés dans Documents\\Zoom : supprime ceux qui ne servent plus.", "zoom", "zoomus"),
        App("OBS Studio", Media,
            "Un logiciel libre pour enregistrer l'écran et faire des lives (Twitch, YouTube).",
            "Le logiciel est léger ; ce sont tes enregistrements (souvent dans Vidéos) qui prennent de la place.",
            "obsstudio", "obs"),
        App("VLC", Media, "Un lecteur vidéo et audio gratuit qui lit presque tous les formats.", "Léger : inutile d'y toucher.", "vlc", "videolan"),
        App("CapCut", Media, "Un logiciel de montage vidéo (ByteDance).", "Les projets et leurs caches peuvent être lourds : vide le cache depuis les paramètres de CapCut.", "capcut"),

        // Drivers and hardware
        App("NVIDIA", Driver,
            "Les pilotes de ta carte graphique NVIDIA et leurs outils (NVIDIA App, GeForce Experience).",
            "Garde les pilotes. Le cache des shaders (DXCache, GLCache) peut être vidé sans risque, et les anciens installateurs de pilotes dans NVIDIA Corporation\\Installer2 prennent parfois beaucoup de place.",
            "nvidia", "nvidiacorporation", "geforceexperience", "nvidiaapp"),
        App("AMD Software", Driver,
            "Les pilotes de ta carte graphique ou de ton processeur AMD (Adrenalin).",
            "Garde les pilotes. Le dossier C:\\AMD contient souvent d'anciens installateurs qui peuvent être supprimés.",
            "amd", "amdsoftware", "radeon"),
        App("Intel", Driver, "Les pilotes et utilitaires Intel (graphique, Wi-Fi, chipset).", "À garder : ils font fonctionner ton matériel.", "intel", "intelcorporation"),
        App("MSI", Driver,
            "Les logiciels de MSI pour ta carte mère ou ta carte graphique (MSI Center, Dragon Center, Afterburner).",
            "Utiles pour l'éclairage, les ventilateurs ou l'overclocking. Désinstalle-les si tu ne t'en sers pas.",
            "msi", "msicenter", "msiafterburner", "dragoncenter"),
        App("Logitech G HUB", Driver, "Le logiciel des souris, claviers et casques Logitech G.", "À garder si tu utilises ces périphériques.", "logitechghub", "logitech", "lghub"),
        App("Razer Synapse", Driver, "Le logiciel des périphériques Razer.", "À garder si tu utilises ces périphériques.", "razersynapse", "razer"),
        App("Corsair iCUE", Driver, "Le logiciel des périphériques et de l'éclairage Corsair.", "À garder si tu utilises ces périphériques.", "corsairicue", "corsair", "icue"),
        App("SteelSeries GG", Driver, "Le logiciel des périphériques SteelSeries.", "À garder si tu utilises ces périphériques.", "steelseriesgg", "steelseries"),

        // Development
        App("Visual Studio Code", Dev,
            "Un éditeur de code gratuit de Microsoft.",
            "Les extensions (dossier .vscode) et le cache peuvent grossir : désinstalle les extensions inutiles depuis VS Code.",
            "microsoftvscode", "visualstudiocode", "vscode", "code"),
        App("Visual Studio", Dev,
            "L'environnement de développement de Microsoft pour .NET, C++ et plus.",
            "Très lourd : utilise Visual Studio Installer pour retirer les composants (charges de travail) inutiles.",
            "microsoftvisualstudio", "visualstudio"),
        App("Cursor", Dev, "Un éditeur de code basé sur VS Code avec de l'IA intégrée.", "Désinstalle les extensions inutiles depuis Cursor.", "cursor"),
        App("JetBrains", Dev, "Les environnements de développement JetBrains (IntelliJ, Rider, WebStorm, PyCharm…).", "Supprime les anciennes versions via JetBrains Toolbox ; leurs caches se recréent.", "jetbrains", "jetbrainstoolbox"),
        App("Git", Dev, "L'outil de gestion de versions utilisé par les développeurs.", "Léger : à garder si tu développes.", "git"),
        App("Node.js", Dev, "L'environnement pour exécuter du JavaScript hors du navigateur.", "Le cache npm (npm-cache) peut être vidé avec « npm cache clean --force ».", "nodejs", "node"),
        App("Python", Dev, "Le langage de programmation Python.", "Chaque version installée prend de la place : désinstalle les anciennes depuis Paramètres › Applications.", "python"),
        App("Java", Dev, "L'environnement d'exécution Java (JRE/JDK), nécessaire à certains logiciels et à Minecraft Java.", "Désinstalle les anciennes versions depuis Paramètres › Applications.", "java", "eclipseadoptium", "jdk"),
        App("Docker Desktop", Dev,
            "Un outil pour faire tourner des conteneurs (environnements isolés) sur Windows.",
            "Les images et conteneurs peuvent prendre des dizaines de Go : nettoie-les depuis Docker Desktop (Troubleshoot › Clean / Purge data) ou avec « docker system prune ».",
            "docker", "dockerdesktop"),
        App("PostgreSQL", Dev, "Un système de base de données.", "Les données des bases sont précieuses : ne supprime rien sans sauvegarde. Désinstalle-le si tu ne t'en sers plus.", "postgresql", "postgres"),
        App("Unity", Dev, "Un moteur de création de jeux vidéo.", "Unity Hub permet de retirer les anciennes versions de l'éditeur, qui pèsent plusieurs Go chacune.", "unity", "unityhub"),
        App("Unreal Engine", Dev, "Le moteur de création de jeux vidéo d'Epic Games.", "Chaque version pèse des dizaines de Go : retire les anciennes depuis le lanceur Epic Games.", "unrealengine", "ue5", "ue4"),
        App("Android Studio", Dev, "L'environnement de développement d'applications Android.", "Les émulateurs (AVD) et le SDK prennent beaucoup de place : supprime les émulateurs inutiles depuis le Device Manager.", "androidstudio", "android"),

        // Creative, office, utilities, cloud
        App("Blender", Creative, "Un logiciel gratuit de 3D (modélisation, animation, rendu).", "Léger ; ce sont tes projets et rendus qui prennent de la place.", "blender", "blenderfoundation"),
        App("Adobe", Creative, "Les logiciels Adobe (Creative Cloud, Photoshop, Premiere Pro, Acrobat…).", "Le cache média de Premiere et After Effects peut être vidé depuis leurs préférences ; désinstalle les applications via Creative Cloud.", "adobe", "adobecreativecloud"),
        App("Microsoft Office", Office, "La suite bureautique de Microsoft (Word, Excel, PowerPoint, Outlook).", "À garder si tu l'utilises. Les fichiers Outlook (.pst, .ost) peuvent être gros.", "microsoftoffice", "office", "office16", "microsoft365"),
        App("OneDrive", Cloud, "Le stockage en ligne de Microsoft, synchronisé avec ton PC.", "Active « Libérer de l'espace » (fichiers à la demande) sur les dossiers peu utilisés : ils restent en ligne sans occuper le disque.", "onedrive", "microsoftonedrive"),
        App("Google Drive", Cloud, "Le stockage en ligne de Google.", "Utilise le mode « Streaming » pour garder les fichiers en ligne sans les télécharger.", "googledrive", "drivefs"),
        App("Dropbox", Cloud, "Un service de stockage en ligne.", "Active la synchronisation sélective pour ne garder en local que ce dont tu as besoin.", "dropbox"),
        App("7-Zip", Utility, "Un logiciel gratuit pour compresser et extraire des archives.", "Très léger : inutile d'y toucher.", "7zip"),
        App("WinRAR", Utility, "Un logiciel pour compresser et extraire des archives.", "Très léger : inutile d'y toucher.", "winrar"),
        App("TeamViewer", Utility, "Un logiciel de prise de contrôle à distance.", "Désinstalle-le si tu ne t'en sers pas : il reste souvent lancé au démarrage.", "teamviewer"),
        App("AnyDesk", Utility, "Un logiciel de prise de contrôle à distance.", "Désinstalle-le si tu ne t'en sers pas.", "anydesk"),
        App("VirtualBox", Utility, "Un logiciel pour faire tourner d'autres systèmes dans des machines virtuelles.", "Les disques virtuels (.vdi) peuvent peser des dizaines de Go : supprime les machines inutiles depuis VirtualBox.", "virtualbox", "oraclevirtualbox"),
        App("VMware", Utility, "Un logiciel de machines virtuelles.", "Supprime les machines virtuelles inutiles depuis VMware pour récupérer leurs disques virtuels.", "vmware"),
        App("Wallpaper Engine", Utility, "Un logiciel de fonds d'écran animés (Steam).", "Les fonds téléchargés depuis le Workshop peuvent être lourds : désabonne-toi de ceux que tu n'utilises plus.", "wallpaperengine"),
    ];

    private static AppProfile App(string name, string category, string whatItIs, string whereSpaceGoes, params string[] keys) =>
        new(name, category, whatItIs, whereSpaceGoes, keys);
}
