namespace Clean.Core.Developer;

// RequiredSibling: a file that must sit next to the folder (by exact name, or "*.ext") for it to be what
// we think it is. Without it a folder called "bin" or "target" could be anything.
public sealed record DevFolderKind(
    string Id,
    string FolderName,
    string RequiredSibling,
    string Title,
    string Explanation,
    string HowToRestore)
{
    public static IReadOnlyList<DevFolderKind> All { get; } =
    [
        new("NODE_MODULES", "node_modules", "package.json", "Dépendances JavaScript (node_modules)",
            "Les paquets que npm a téléchargés pour ce projet. Rien de ce que tu as écrit n'est dedans.",
            "npm install"),
        new("DOTNET_BIN", "bin", "*.csproj", "Programme compilé (.NET, bin)",
            "Le résultat de la compilation d'un projet .NET.",
            "Recompiler le projet"),
        new("DOTNET_OBJ", "obj", "*.csproj", "Fichiers intermédiaires (.NET, obj)",
            "Ce que .NET prépare avant de compiler.",
            "Recompiler le projet"),
        new("DOTNET_BIN_FS", "bin", "*.fsproj", "Programme compilé (F#, bin)",
            "Le résultat de la compilation d'un projet F#.",
            "Recompiler le projet"),
        new("DOTNET_OBJ_FS", "obj", "*.fsproj", "Fichiers intermédiaires (F#, obj)",
            "Ce que F# prépare avant de compiler.",
            "Recompiler le projet"),
        new("DOTNET_BIN_VB", "bin", "*.vbproj", "Programme compilé (VB.NET, bin)",
            "Le résultat de la compilation d'un projet VB.NET.",
            "Recompiler le projet"),
        new("DOTNET_OBJ_VB", "obj", "*.vbproj", "Fichiers intermédiaires (VB.NET, obj)",
            "Ce que VB.NET prépare avant de compiler.",
            "Recompiler le projet"),
        new("PYCACHE", "__pycache__", string.Empty, "Cache Python (__pycache__)",
            "Du code Python déjà traduit pour démarrer plus vite.",
            "Python le recrée au prochain lancement"),
        new("CARGO_TARGET", "target", "Cargo.toml", "Compilation Rust (target)",
            "Tout ce que Cargo a compilé pour ce projet. Ces dossiers dépassent souvent plusieurs Go.",
            "cargo build"),
        new("MAVEN_TARGET", "target", "pom.xml", "Compilation Maven (target)",
            "Le résultat de la compilation d'un projet Java.",
            "mvn package"),
        new("GRADLE_BUILD", "build", "build.gradle", "Compilation Gradle (build)",
            "Le résultat de la compilation d'un projet Gradle.",
            "gradle build"),
        new("GRADLE_BUILD_KTS", "build", "build.gradle.kts", "Compilation Gradle (build)",
            "Le résultat de la compilation d'un projet Gradle.",
            "gradle build"),
        new("GRADLE_CACHE", ".gradle", "settings.gradle", "Cache Gradle du projet (.gradle)",
            "Ce que Gradle garde en mémoire pour ce projet.",
            "Gradle le recrée"),
        new("GRADLE_CACHE_KTS", ".gradle", "settings.gradle.kts", "Cache Gradle du projet (.gradle)",
            "Ce que Gradle garde en mémoire pour ce projet.",
            "Gradle le recrée"),
        new("NEXT_CACHE", ".next", "package.json", "Compilation Next.js (.next)",
            "Les pages que Next.js a déjà préparées.",
            "npm run build"),
        new("NUXT_CACHE", ".nuxt", "package.json", "Compilation Nuxt (.nuxt)",
            "Les pages que Nuxt a déjà préparées.",
            "npm run dev ou npm run build"),
        new("SVELTEKIT_CACHE", ".svelte-kit", "package.json", "Compilation SvelteKit (.svelte-kit)",
            "Les fichiers que SvelteKit a déjà préparés.",
            "npm run dev ou npm run build"),
    ];
}
